## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [1]:
import numpy as np
#1
a = np.zeros((8, 8), dtype=int)
a = np.vstack([np.ones(8, dtype=int), a])
a = np.vstack([a, np.ones(8, dtype=int)])
a = np.hstack([np.ones((10, 1), dtype=int), a])
np.hstack([a, np.ones((10, 1), dtype=int)])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

2. Create a 5*5 matrix with each row being 0 to 4

In [2]:
#2
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [3]:
#3
a = np.array([[0, 1], [1, 0]])
np.tile(a, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [4]:
#4
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[a%2 == 1]

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix 

In [5]:
#5
a = np.random.rand(5, 5)
a -= np.mean(a)
a /= np.std(a)
a

array([[-0.38211633,  1.66142011, -1.10101393,  1.08534839, -0.534766  ],
       [-0.87403007,  0.47493666,  0.38045703, -0.36454941,  1.55445781],
       [ 0.90819509,  0.84020649, -1.04836356, -1.26988707, -1.38885973],
       [-0.08226932,  0.21362302, -0.99461267,  0.15288437,  1.51575719],
       [-0.50506126, -1.77967852,  1.62937844,  0.19787064, -0.28932737]])

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [6]:
#6
c = np.random.rand(10, 2)
d = np.hypot(c[:,0], c[:,1])
r = np.arctan2(c[:,1], c[:,0])
d, r

(array([0.43679155, 0.94117033, 0.83296457, 1.18279739, 1.01309448,
        0.14375847, 1.04789925, 0.80793   , 0.98937445, 1.02673747]),
 array([0.30320034, 1.30810072, 1.46750105, 0.98829245, 0.91936092,
        1.08705016, 0.44595433, 1.45415938, 1.11020306, 0.54734367]))

7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [8]:
#7
np.insert([1, 2, 3, 4, 5], np.tile(np.arange(1, 5), 3), np.zeros(12))

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [9]:
#8
0*np.nan, np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, np.nan in set([np.nan]), 0.3 == 3 * 0.1

(nan, False, False, nan, True, False)

9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [10]:
#9
np.array(0)/np.array(0), np.array(0)//np.array(0), np.array([np.nan]).astype(int).astype(float)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_34464\1011324921.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0)/np.array(0), np.array(0)//np.array(0), np.array([np.nan]).astype(int).astype(float)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_34464\1011324921.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)/np.array(0), np.array(0)//np.array(0), np.array([np.nan]).astype(int).astype(float)


(nan, 0, array([-2.14748365e+09]))